#!/bin/bash
HOST='ftp://richana.eu'
USER='mrichana'
PASS='R0b3rt!n0'
TARGETFOLDER='/patients'
SOURCEFOLDER='/home/mrichana/Projects/medPatients/dist/'

lftp -f "
open $HOST
user $USER $PASS
lcd $SOURCEFOLDER
mirror -c -e -R --verbose $SOURCEFOLDER $TARGETFOLDER
bye
"

